model_type: t5-small
epochs: 1
max_len: 100
model_save_name: t5-small.pt
datasets_path: data/processed
metrics_file: metrics.csv
oversampling: true
clear_models_dir: true
early_stopping: true

sec_label: "true"
nonsec_label: "false"

validation: cross-validation
# cross-validation: stratified cross-validation, test_datasets are ignored
# p-validation: training on one projects and testing on others 
train_datasets:
  secreq:
    - CPN
    - GPS
valid_datasets:
  secreq:
    - ePurse-selective
